### ISSUE TITLE
Var reference issue

### ISSUE THREAD

**Issue by mbauer599** [andrewelick/amazon-giveaway-bot#4]
Ubuntu 16.04, all reqs should be there// Ideas? 

Could not load page
Traceback (most recent call last):
  File "amazoncontest.py", line 380, in <module>
    load_login_info()
  File "amazoncontest.py", line 371, in load_login_info
    amazon_bot(email, password, name, want_follow)
  File "amazoncontest.py", line 326, in amazon_bot
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment

**Comment by mbauer599** [comment]
This issue can be closed. I'm using an older version of geckodriver and it was breaking the python3 version of selenium. Recomend putting in some form of logging in try loops so we can know where it breaks.
