### ISSUE TITLE
Having an issue loading prizes

### ISSUE THREAD

**Issue by ryanrohypnol** [andrewelick/amazon-giveaway-bot#9]
I created a Firefox profile, I installed all requirements but am having some issues loading items, would love to see this work!

> 

Loading prizes
Could not load items

Loading prizes
Could not load items

Loading prizes
Could not load items

Loading prizes
Could not load items

Loading prizes
Could not load items

Loading prizes

>

**Comment by SlickStretch** [comment]
Same.

**Comment by SlickStretch** [comment]
Same.

**Comment by ryanrohypnol** [comment]
It's prob just an issue with how he's scraping the giveaway data from https://www.giveawaylisting.com/index2.html

That's my guess, hopefully he replies soon!

**Comment by SlickStretch** [comment]
Not sure if it's helpful or not, but when I attempt to interrupt with ctrl+c in IDLE, I get the following:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Working\Amazon Bot\amazoncontest.py", line 24, in amazon_bot
    response = get("view-source:https://www.giveawaylisting.com/index2.html")
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'view-source:https://www.giveawaylisting.com/index2.html'
```
